* =dwl-guile=
This project patches [[https://github.com/djpohly/dwl][ =dwl= ]] to load a startup configuration file written in [[https://www.gnu.org/software/guile/][GNU Guile]].

** Goal
The main goal of =dwl-guile= is to serve as a minimal =dwm=-like Wayland compositor for those who use [[https://guix.gnu.org/][GNU Guix System]] - a GNU/Linux distribution in which the user can customize and configure their entire system in GNU Guile.

With =dwl-guile=, we can integrate the window manager customization with that of the rest of the system, which allows for a dynamic, programmable and reproducible configuration for our entire computing environment --- all in Guile.

** Installation
The best way to install and use =dwl-guile= is through our Guix channel  [[https://github.com/engstrand-config/home-service-dwl-guile][home-service-dwl-guile]], which (as the name suggests) provides a [[https://guix.gnu.org/manual/devel/en/html_node/Home-Configuration.html][Guix Home]] service for =dwl-guile=.

Non-Guix System users can download the GNU Guix package manager for their respective GNU/Linux distributions in order to configure and run =dwl-guile= through our Guix Home service.
An alternative way (that works without the Guix package manager) would be to
1. Clone the repositories for base =dwl= and for =dwl-guile=
2. Patch =dwl= with the =dwl-guile= patch
3. Build the binary with the help of the =Makefile= found in this repository
4. Supply the produced binary with a Guile configuration file

** Releases
The [[https://github.com/engstrand-config/dwl-guile/releases][Releases]] section contains
- the main =dwl-guile= patch
  - this includes the =keycode=, =smartborders=, =vanitygaps=, =cyclelayout= and =alpha= patches by default.
- the =dwl= patches =attachabove=, =monitor-config=, =movestack=, =swallow= and =xwayland=, edited for =dwl-guile=
